version: 0.2
phases:
  install:
    commands:
      - gem install bundler -v 1.17.2
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
artifacts:
  # Tells AWS CodeBuild how to drop the files into S3.
  base-directory: '_dist'
  files:
    - '**/*'